//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick.Order.AppCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quick.Order.AppCore.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account creation.
        /// </summary>
        public static string AccountCreation {
            get {
                return ResourceManager.GetString("AccountCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a dish.
        /// </summary>
        public static string AddDish {
            get {
                return ResourceManager.GetString("AddDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a section.
        /// </summary>
        public static string AddSection {
            get {
                return ResourceManager.GetString("AddSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly and simply order..
        /// </summary>
        public static string AppCatchPhrase {
            get {
                return ResourceManager.GetString("AppCatchPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a restaurant ?.
        /// </summary>
        public static string AreYouARestaurant {
            get {
                return ResourceManager.GetString("AreYouARestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteCommand.
        /// </summary>
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete restaurant.
        /// </summary>
        public static string DeleteRestaurant {
            get {
                return ResourceManager.GetString("DeleteRestaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish description.
        /// </summary>
        public static string DishDescription {
            get {
                return ResourceManager.GetString("DishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish name.
        /// </summary>
        public static string DishName {
            get {
                return ResourceManager.GetString("DishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit dish.
        /// </summary>
        public static string EditDish {
            get {
                return ResourceManager.GetString("EditDish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status.
        /// </summary>
        public static string EditOrderStatus {
            get {
                return ResourceManager.GetString("EditOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password ?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate QR Code.
        /// </summary>
        public static string GenerateQr {
            get {
                return ResourceManager.GetString("GenerateQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for command.
        /// </summary>
        public static string NameForCommand {
            get {
                return ResourceManager.GetString("NameForCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no orders..
        /// </summary>
        public static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No restaurant created..
        /// </summary>
        public static string NoRestaurantCreated {
            get {
                return ResourceManager.GetString("NoRestaurantCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order is being prepared.
        /// </summary>
        public static string OrderInProgress {
            get {
                return ResourceManager.GetString("OrderInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order pending.
        /// </summary>
        public static string OrderPending {
            get {
                return ResourceManager.GetString("OrderPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ready to be collected ✅.
        /// </summary>
        public static string OrderReady {
            get {
                return ResourceManager.GetString("OrderReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending orders.
        /// </summary>
        public static string OrdersReceived {
            get {
                return ResourceManager.GetString("OrdersReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or sign in with.
        /// </summary>
        public static string OrSignInWith {
            get {
                return ResourceManager.GetString("OrSignInWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant informations.
        /// </summary>
        public static string RestaurantInfos {
            get {
                return ResourceManager.GetString("RestaurantInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant name.
        /// </summary>
        public static string RestaurantName {
            get {
                return ResourceManager.GetString("RestaurantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan to order.
        /// </summary>
        public static string ScanToOrder {
            get {
                return ResourceManager.GetString("ScanToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section name.
        /// </summary>
        public static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up or sign in to manage your restaurant..
        /// </summary>
        public static string SignInOrUp {
            get {
                return ResourceManager.GetString("SignInOrUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up..
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table number.
        /// </summary>
        public static string TableNumber {
            get {
                return ResourceManager.GetString("TableNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an account ?.
        /// </summary>
        public static string YouHaveNoAccount {
            get {
                return ResourceManager.GetString("YouHaveNoAccount", resourceCulture);
            }
        }
    }
}
