//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick.Order.AppCore.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Quick.Order.AppCore.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string AccountCreation {
            get {
                return ResourceManager.GetString("AccountCreation", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AddDish {
            get {
                return ResourceManager.GetString("AddDish", resourceCulture);
            }
        }
        
        public static string AddSection {
            get {
                return ResourceManager.GetString("AddSection", resourceCulture);
            }
        }
        
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        public static string AppCatchPhrase {
            get {
                return ResourceManager.GetString("AppCatchPhrase", resourceCulture);
            }
        }
        
        public static string AreYouARestaurant {
            get {
                return ResourceManager.GetString("AreYouARestaurant", resourceCulture);
            }
        }
        
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string DeleteCommand {
            get {
                return ResourceManager.GetString("DeleteCommand", resourceCulture);
            }
        }
        
        public static string DeleteRestaurant {
            get {
                return ResourceManager.GetString("DeleteRestaurant", resourceCulture);
            }
        }
        
        public static string DishDescription {
            get {
                return ResourceManager.GetString("DishDescription", resourceCulture);
            }
        }
        
        public static string DishName {
            get {
                return ResourceManager.GetString("DishName", resourceCulture);
            }
        }
        
        public static string EditDish {
            get {
                return ResourceManager.GetString("EditDish", resourceCulture);
            }
        }
        
        public static string EditOrderStatus {
            get {
                return ResourceManager.GetString("EditOrderStatus", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string GenerateQr {
            get {
                return ResourceManager.GetString("GenerateQr", resourceCulture);
            }
        }
        
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        public static string NameForCommand {
            get {
                return ResourceManager.GetString("NameForCommand", resourceCulture);
            }
        }
        
        public static string NoOrders {
            get {
                return ResourceManager.GetString("NoOrders", resourceCulture);
            }
        }
        
        public static string NoRestaurantCreated {
            get {
                return ResourceManager.GetString("NoRestaurantCreated", resourceCulture);
            }
        }
        
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        public static string OrdersReceived {
            get {
                return ResourceManager.GetString("OrdersReceived", resourceCulture);
            }
        }
        
        public static string OrSignInWith {
            get {
                return ResourceManager.GetString("OrSignInWith", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        public static string RestaurantInfos {
            get {
                return ResourceManager.GetString("RestaurantInfos", resourceCulture);
            }
        }
        
        public static string RestaurantName {
            get {
                return ResourceManager.GetString("RestaurantName", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ScanToOrder {
            get {
                return ResourceManager.GetString("ScanToOrder", resourceCulture);
            }
        }
        
        public static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        public static string SignInOrUp {
            get {
                return ResourceManager.GetString("SignInOrUp", resourceCulture);
            }
        }
        
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        public static string TableNumber {
            get {
                return ResourceManager.GetString("TableNumber", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string YouHaveNoAccount {
            get {
                return ResourceManager.GetString("YouHaveNoAccount", resourceCulture);
            }
        }
        
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        public static string OrderPending {
            get {
                return ResourceManager.GetString("OrderPending", resourceCulture);
            }
        }
        
        public static string OrderInProgress {
            get {
                return ResourceManager.GetString("OrderInProgress", resourceCulture);
            }
        }
        
        public static string OrderReady {
            get {
                return ResourceManager.GetString("OrderReady", resourceCulture);
            }
        }
        
        public static string ChangeAppLanguage {
            get {
                return ResourceManager.GetString("ChangeAppLanguage", resourceCulture);
            }
        }
        
        public static string PrintQrCode {
            get {
                return ResourceManager.GetString("PrintQrCode", resourceCulture);
            }
        }
        
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        public static string OrderRecap {
            get {
                return ResourceManager.GetString("OrderRecap", resourceCulture);
            }
        }
        
        public static string NoArticleOrdered {
            get {
                return ResourceManager.GetString("NoArticleOrdered", resourceCulture);
            }
        }
        
        public static string ValidateOrder {
            get {
                return ResourceManager.GetString("ValidateOrder", resourceCulture);
            }
        }
        
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        public static string ResetPasswordEmailAlert {
            get {
                return ResourceManager.GetString("ResetPasswordEmailAlert", resourceCulture);
            }
        }
        
        public static string ConnectionRestored {
            get {
                return ResourceManager.GetString("ConnectionRestored", resourceCulture);
            }
        }
        
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        public static string OrdersReceived_Duplicate_1_ {
            get {
                return ResourceManager.GetString("OrdersReceived_Duplicate[1]", resourceCulture);
            }
        }
        
        public static string RestaurantWasDeleted {
            get {
                return ResourceManager.GetString("RestaurantWasDeleted", resourceCulture);
            }
        }
        
        public static string UserCreationSuccess {
            get {
                return ResourceManager.GetString("UserCreationSuccess", resourceCulture);
            }
        }
        
        public static string InvalidDishAlert {
            get {
                return ResourceManager.GetString("InvalidDishAlert", resourceCulture);
            }
        }
        
        public static string InvalidDishSectionAlert {
            get {
                return ResourceManager.GetString("InvalidDishSectionAlert", resourceCulture);
            }
        }
        
        public static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        public static string DishDeletionPrompt {
            get {
                return ResourceManager.GetString("DishDeletionPrompt", resourceCulture);
            }
        }
        
        public static string DishSectionDeletionPrompt {
            get {
                return ResourceManager.GetString("DishSectionDeletionPrompt", resourceCulture);
            }
        }
        
        public static string RestoreInternetConnectionAlert {
            get {
                return ResourceManager.GetString("RestoreInternetConnectionAlert", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string RestaurantDeletionPrompt {
            get {
                return ResourceManager.GetString("RestaurantDeletionPrompt", resourceCulture);
            }
        }
        
        public static string OrderPageTitle {
            get {
                return ResourceManager.GetString("OrderPageTitle", resourceCulture);
            }
        }
        
        public static string ContinueOrder {
            get {
                return ResourceManager.GetString("ContinueOrder", resourceCulture);
            }
        }
        
        public static string DeleteOrderPrompt {
            get {
                return ResourceManager.GetString("DeleteOrderPrompt", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
    }
}
